### ISSUE TITLE
tibwars crash when pressing the game browser on client

### ISSUE THREAD

**Issue by erubianwarlord** [Medstar117/CNC-Ultimate-Collection-Fixed-Launchers#7]
i installed as directed and clicked the browser button as to open the page for mod but it immediately crashes to desktop

**Comment by Medstar117** [comment]
That would be an issue with the game's launcher (CNC3.exe), not the fixed launchers in this installer (CNC3Launcher.exe).

If you're trying to use the mod browser, and it's crashing to the desktop, try removing the replays from your Replays folder.
