### ISSUE TITLE
Does not detect C&C3TW with Proton/Linux

### ISSUE THREAD

**Issue by wren-cal** [Medstar117/CNC-Ultimate-Collection-Fixed-Launchers#8]
Attempting to launch the program using Proton on Linux results in the program not being able to detect Steam-installed C&C3TW on Linux.

Upon launching the program using the following command:
```
wren@NullifiedWorkstation ~/.steam/root/steamapps/compatdata/24790/pfx $ STEAM_COMPAT_DATA_PATH="$HOME/.steam/root/steamapps/compatdata/24790/" WINEPREFIX=$PWD  $HOME/.steam/root/steamapps/common/Proton\ 5.13/proton run "Fixed C&C Ultimate Collection Launchers Installer.exe"
```
 and going to "Choose Games," not a single fixed launcher can be installed. It seems that the solution to this would be to check the contents of `C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf`, as it shows all library folders where C&C could be installed through Steam.

**Comment by Medstar117** [comment]
Your issue is that you are trying to use these on a Steam installation. These are for The Ultimate Collection on Origin.

It checks specifically like this so that Steam users don't install these by accident.
